const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

exports.generateServiceReport = (request, res) => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=ServiceReport-${request._id}.pdf`);

  doc.pipe(res);

  // ── Header ──────────────────────────────────────────────
  doc.rect(0, 0, doc.page.width, 80).fill('#1a2332');
  doc.fill('#ffffff').fontSize(22).font('Helvetica-Bold')
    .text('⚡ ServicePro — Service Report', 50, 28, { align: 'center' });
  doc.moveDown(2);

  // ── Report Meta ─────────────────────────────────────────
  doc.fill('#333333').fontSize(11).font('Helvetica');
  doc.text(`Report ID : ${request._id}`);
  doc.text(`Generated : ${new Date().toLocaleString()}`);
  doc.text(`Status    : ${request.status.toUpperCase()}`);
  doc.moveDown();

  // ── Customer Info ────────────────────────────────────────
  doc.font('Helvetica-Bold').fontSize(13).fill('#4F46E5').text('Customer Details', { underline: false });
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#4F46E5').stroke();
  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(11).fill('#333333');
  doc.text(`Name  : ${request.userId?.name || 'N/A'}`);
  doc.text(`Email : ${request.userId?.email || 'N/A'}`);
  if (request.userId?.phone) doc.text(`Phone : ${request.userId.phone}`);
  doc.moveDown();

  // ── Provider Info ────────────────────────────────────────
  doc.font('Helvetica-Bold').fontSize(13).fill('#4F46E5').text('Service Provider');
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#4F46E5').stroke();
  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(11).fill('#333333');
  doc.text(`Name           : ${request.assignedTo?.name || 'Not yet assigned'}`);
  doc.text(`Role           : ${request.assignedTo?.role || 'N/A'}`);
  doc.text(`Email          : ${request.assignedTo?.email || 'N/A'}`);
  if (request.assignedTo?.specialization)
    doc.text(`Specialization : ${request.assignedTo.specialization}`);
  doc.moveDown();

  // ── Job Details ──────────────────────────────────────────
  doc.font('Helvetica-Bold').fontSize(13).fill('#4F46E5').text('Job Details');
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#4F46E5').stroke();
  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(11).fill('#333333');
  doc.text(`Service Type : ${request.serviceType}`);
  doc.text(`Urgency      : ${request.urgency?.toUpperCase()}`);
  doc.text(`Location     : ${request.location}`);
  doc.text(`Description  : ${request.description}`);
  if (request.completedAt)
    doc.text(`Completed At : ${new Date(request.completedAt).toLocaleString()}`);
  if (request.notes)
    doc.text(`Notes        : ${request.notes}`);
  doc.moveDown();

  // ── Fault Photo ──────────────────────────────────────────
  if (request.faultPhoto) {
    // faultPhoto is stored as "/uploads/faults/filename.jpg"
    const photoPath = path.join(__dirname, '..', request.faultPhoto.replace(/^\//, ''));

    if (fs.existsSync(photoPath)) {
      doc.font('Helvetica-Bold').fontSize(13).fill('#4F46E5').text('Fault Photo');
      doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#4F46E5').stroke();
      doc.moveDown(0.5);

      try {
        // Fit image within page width, max height 300
        doc.image(photoPath, { fit: [480, 300], align: 'center' });
        doc.moveDown();
      } catch (imgErr) {
        doc.font('Helvetica').fill('#999999').text('[Photo could not be embedded]');
      }
    } else {
      doc.font('Helvetica').fill('#999999').text('Fault photo file not found on server.');
    }
  }

  // ── Footer ───────────────────────────────────────────────
  doc.moveDown();
  doc.fontSize(9).fill('#999999')
    .text('This report was auto-generated by ServicePro. For queries, contact support.', { align: 'center' });

  doc.end();
};
